/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ids;

/**
 * This class will create a packet and send it to server 
 * @author madhura phatak
 * version 1.0
 */
public class CreateSendPacket extends javax.swing.JFrame {
    
    private long duration_in;
    private String protocol_type_in;
    private String service_in;
    private String flag_in;
    private long src_bytes_in;
    private long dst_bytes_in;
    private int	land_in;
    private int	wrong_fragment_in;
    private int	urgent_in;
    private int	hot_in;
    private int	num_failed_logins_in;
    private int	logged_in;
    private int	num_compromised_in;
    private int	root_shell_in;
    private int	su_attempted_in;
    private int	num_root_in;
    private int	num_file_creations_in;
    private int	num_shells_in;
    private int	num_access_files_in;
    private int	num_outbound_cmds_in;
    private int	is_host_login_in;
    private int	is_guest_login_in;
    private int	count_in;
    private int	srv_count_in;
    private float serror_rate_in;
    private float srv_serror_rate_in;
    private float rerror_rate_in;
    private float srv_rerror_rate_in;
    private float same_srv_rate_in;
    private float diff_srv_rate_in;
    private float srv_diff_host_rate_in;
    private int	dst_host_count_in;
    private int	dst_host_srv_count_in;
    private float dst_host_same_srv_rate_in;
    private float dst_host_diff_srv_rate_in;
    private float dst_host_same_src_port_rate_in;
    private float dst_host_srv_diff_host_rate_in;
    private float dst_host_serror_rate_in;
    private float dst_host_srv_serror_rate_in;
    private float dst_host_rerror_rate_in;
    private float dst_host_srv_rerror_rate_in;
    
    Packet p1 = new Packet();
    Client c2 = new Client();
    /**
     * Creates new form CreateSendPacket
     */
    public CreateSendPacket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Duration_in = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Protocol_type_in = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Flag_in = new javax.swing.JComboBox();
        Src_bytes_in = new javax.swing.JComboBox();
        Dst_bytes_in = new javax.swing.JComboBox();
        Land_in = new javax.swing.JComboBox();
        Wrong_fragment_in = new javax.swing.JComboBox();
        Urgent_in = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hot_in = new javax.swing.JComboBox();
        Num_failed_logins_in = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Logged_in = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        Num_compromised_in = new javax.swing.JComboBox();
        Root_shell_in = new javax.swing.JComboBox();
        Su_attempted_in = new javax.swing.JComboBox();
        Num_root_in = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Num_file_creations_in = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Num_access_files_in = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        Num_outbound_cmds_in = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        Is_host_login_in = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        Is_guest_login_in = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        Count_in = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        Srv_count_in = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        Serror_rate_in = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        Srv_serror_rate_in = new javax.swing.JComboBox();
        Rerror_rate_in = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        Srv_Rerror_rate_in = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        Same_srv_rate_in = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        Diff_srv_rate_in = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        Srv_diff_host_rate_in = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        Dst_host_count_in = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        Dst_host_srv_count_in = new javax.swing.JComboBox();
        Dst_host_same_srv_rate_in = new javax.swing.JComboBox();
        Dst_host_same_src_port_rate_in = new javax.swing.JComboBox();
        Dst_host_srv_diff_host_rate_in = new javax.swing.JComboBox();
        Dst_host_serror_rate_in = new javax.swing.JComboBox();
        Dst_host_srv_serror_rate_in = new javax.swing.JComboBox();
        Dst_host_rerror_rate_in = new javax.swing.JComboBox();
        Dst_host_srv_rerror_rate_in = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Service_in = new javax.swing.JComboBox();
        Num_shells_in = new javax.swing.JComboBox();
        Dst_host_diff_srv_rate_in = new javax.swing.JComboBox();
        SendPacket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DURATION");

        Duration_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--", "Item 1", "Item 2", "Item 3", "Item 4" }));
        Duration_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Duration_inActionPerformed(evt);
            }
        });

        jLabel2.setText("PROTOCOL_TYPE");

        Protocol_type_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Protocol_type_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Protocol_type_inActionPerformed(evt);
            }
        });

        jLabel3.setText("SERVICE");

        Flag_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Flag_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flag_inActionPerformed(evt);
            }
        });

        Src_bytes_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Src_bytes_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Src_bytes_inActionPerformed(evt);
            }
        });

        Dst_bytes_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_bytes_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_bytes_inActionPerformed(evt);
            }
        });

        Land_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Land_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Land_inActionPerformed(evt);
            }
        });

        Wrong_fragment_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Wrong_fragment_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wrong_fragment_inActionPerformed(evt);
            }
        });

        Urgent_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Urgent_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Urgent_inActionPerformed(evt);
            }
        });

        jLabel4.setText("FLAG");

        jLabel5.setText("SRC_BYTES");

        jLabel6.setText("DST_BYTES");

        jLabel7.setText("LAND");

        jLabel8.setText("WRONG_FRAGMENT");

        jLabel9.setText("URGENT");

        jLabel10.setText("HOT");

        Hot_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Hot_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hot_inActionPerformed(evt);
            }
        });

        Num_failed_logins_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_failed_logins_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_failed_logins_inActionPerformed(evt);
            }
        });

        jLabel11.setText("NUM_FAILED_LOGINS");

        jLabel12.setText("LOGGED_IN");

        Logged_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Logged_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logged_inActionPerformed(evt);
            }
        });

        jLabel13.setText("NUM_COMPROMISED");

        Num_compromised_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_compromised_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_compromised_inActionPerformed(evt);
            }
        });

        Root_shell_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Root_shell_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Root_shell_inActionPerformed(evt);
            }
        });

        Su_attempted_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Su_attempted_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Su_attempted_inActionPerformed(evt);
            }
        });

        Num_root_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_root_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_root_inActionPerformed(evt);
            }
        });

        jLabel14.setText("ROOT_SHELL");

        jLabel15.setText("SU_ATTEMPTED");

        jLabel16.setText("NUM_ROOT");

        jLabel17.setText("NUM_FILE_CREATIONS");

        Num_file_creations_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_file_creations_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_file_creations_inActionPerformed(evt);
            }
        });

        jLabel18.setText("NUM_SHELLS");

        jLabel19.setText("NUM_ACCESS_FILES");

        Num_access_files_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_access_files_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_access_files_inActionPerformed(evt);
            }
        });

        jLabel20.setText("NUM_OUTBOUND_CMDS");

        Num_outbound_cmds_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_outbound_cmds_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_outbound_cmds_inActionPerformed(evt);
            }
        });

        jLabel21.setText("IS_HOST_LOGIN");

        Is_host_login_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Is_host_login_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Is_host_login_inActionPerformed(evt);
            }
        });

        jLabel22.setText("IS_GUEST_LOGIN");

        Is_guest_login_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Is_guest_login_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Is_guest_login_inActionPerformed(evt);
            }
        });

        jLabel23.setText("COUNT");

        Count_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Count_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Count_inActionPerformed(evt);
            }
        });

        jLabel24.setText("SRV_COUNT");

        Srv_count_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Srv_count_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Srv_count_inActionPerformed(evt);
            }
        });

        jLabel25.setText("SERROR_RATE");

        Serror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Serror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Serror_rate_inActionPerformed(evt);
            }
        });

        jLabel26.setText("SRV_SERROR_RATE");

        Srv_serror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Srv_serror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Srv_serror_rate_inActionPerformed(evt);
            }
        });

        Rerror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Rerror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rerror_rate_inActionPerformed(evt);
            }
        });

        jLabel27.setText("RERROR_RATE");

        Srv_Rerror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Srv_Rerror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Srv_Rerror_rate_inActionPerformed(evt);
            }
        });

        jLabel28.setText("SRV_RERROR_RATE");

        Same_srv_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Same_srv_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Same_srv_rate_inActionPerformed(evt);
            }
        });

        jLabel29.setText("SAME_SRV_RATE");

        Diff_srv_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Diff_srv_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diff_srv_rate_inActionPerformed(evt);
            }
        });

        jLabel30.setText("DIFF_SRV_RATE");

        Srv_diff_host_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Srv_diff_host_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Srv_diff_host_rate_inActionPerformed(evt);
            }
        });

        jLabel31.setText("SRV_DIFF_HOST_RATE");

        Dst_host_count_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_count_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_count_inActionPerformed(evt);
            }
        });

        jLabel32.setText("DST_HOST_COUNT");

        Dst_host_srv_count_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_srv_count_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_srv_count_inActionPerformed(evt);
            }
        });

        Dst_host_same_srv_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_same_srv_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_same_srv_rate_inActionPerformed(evt);
            }
        });

        Dst_host_same_src_port_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_same_src_port_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_same_src_port_rate_inActionPerformed(evt);
            }
        });

        Dst_host_srv_diff_host_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_srv_diff_host_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_srv_diff_host_rate_inActionPerformed(evt);
            }
        });

        Dst_host_serror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_serror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_serror_rate_inActionPerformed(evt);
            }
        });

        Dst_host_srv_serror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_srv_serror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_srv_serror_rate_inActionPerformed(evt);
            }
        });

        Dst_host_rerror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_rerror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_rerror_rate_inActionPerformed(evt);
            }
        });

        Dst_host_srv_rerror_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_srv_rerror_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_srv_rerror_rate_inActionPerformed(evt);
            }
        });

        jLabel33.setText("DST_HOST_SRV_COUNT");

        jLabel34.setText("DST_HOST_SAME_SRV_RATE");

        jLabel35.setText("DST_HOST_DIFF_SRV_RATE");

        jLabel36.setText("DST_HOST_SAME_SRC_PORT_RATE");

        jLabel37.setText("DST_HOST_SRV_DIFF_HOST_RATE");

        jLabel38.setText("DST_HOST_SERROR_RATE");

        jLabel39.setText("DST_HOST_SRV_SERROR_RATE");

        jLabel40.setText("DST_HOST_RERROR_RATE");

        jLabel41.setText("DST_HOST_SRV_RERROR_RATE");

        jLabel42.setText("Select Attributes of Packet to create Packet");

        Service_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Service_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Service_inActionPerformed(evt);
            }
        });

        Num_shells_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Num_shells_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_shells_inActionPerformed(evt);
            }
        });

        Dst_host_diff_srv_rate_in.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Dst_host_diff_srv_rate_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dst_host_diff_srv_rate_inActionPerformed(evt);
            }
        });

        SendPacket.setText("Send Packet");
        SendPacket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPacketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Is_host_login_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Duration_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Protocol_type_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Flag_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Src_bytes_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dst_bytes_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Land_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrong_fragment_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Urgent_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hot_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_failed_logins_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logged_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_compromised_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Root_shell_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Su_attempted_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_root_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_file_creations_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_access_files_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_outbound_cmds_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Service_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num_shells_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_srv_rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_srv_serror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_same_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_srv_count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dst_host_count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(110, 110, 110)
                                        .addComponent(Srv_diff_host_rate_in, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Diff_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Same_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Srv_Rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Srv_count_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Srv_serror_rate_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Serror_rate_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Dst_host_serror_rate_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dst_host_srv_diff_host_rate_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel41)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel34)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel35)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Dst_host_diff_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addGap(105, 105, 105)
                                                    .addComponent(Is_guest_login_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39)
                                .addComponent(Dst_host_same_src_port_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(SendPacket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Duration_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Is_guest_login_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Protocol_type_in, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(Count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Srv_count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(Service_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Flag_in, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Serror_rate_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Src_bytes_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Dst_bytes_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(Land_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(Wrong_fragment_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(Urgent_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(Hot_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(Num_failed_logins_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(Logged_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(Num_compromised_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(Root_shell_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(Su_attempted_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(Num_root_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(Num_file_creations_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(Num_shells_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(Num_access_files_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(Num_outbound_cmds_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(Is_host_login_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Srv_serror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Srv_Rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Same_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Diff_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Srv_diff_host_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_srv_count_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_same_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dst_host_diff_srv_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel35)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dst_host_same_src_port_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dst_host_srv_diff_host_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_serror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_srv_serror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dst_host_srv_rerror_rate_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(SendPacket)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Duration_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Duration_inActionPerformed
        duration_in = (Long)Duration_in.getSelectedItem();
    }//GEN-LAST:event_Duration_inActionPerformed

    private void Protocol_type_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Protocol_type_inActionPerformed
        protocol_type_in = Protocol_type_in.getSelectedItem().toString();
    }//GEN-LAST:event_Protocol_type_inActionPerformed

    private void Service_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service_inActionPerformed
        service_in = Service_in.getSelectedItem().toString();
    }//GEN-LAST:event_Service_inActionPerformed

    private void Flag_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flag_inActionPerformed
        flag_in = Flag_in.getSelectedItem().toString();
    }//GEN-LAST:event_Flag_inActionPerformed

    private void Src_bytes_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Src_bytes_inActionPerformed
        src_bytes_in = (Long)Src_bytes_in.getSelectedItem();
    }//GEN-LAST:event_Src_bytes_inActionPerformed

    private void Dst_bytes_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_bytes_inActionPerformed
        dst_bytes_in = (Long)Dst_bytes_in.getSelectedItem();
    }//GEN-LAST:event_Dst_bytes_inActionPerformed

    private void Land_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Land_inActionPerformed
        land_in = (Integer)Land_in.getSelectedItem();
    }//GEN-LAST:event_Land_inActionPerformed

    private void Wrong_fragment_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wrong_fragment_inActionPerformed
        wrong_fragment_in = (Integer)Wrong_fragment_in.getSelectedItem();
    }//GEN-LAST:event_Wrong_fragment_inActionPerformed

    private void Urgent_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Urgent_inActionPerformed
        urgent_in = (Integer)Urgent_in.getSelectedItem();
    }//GEN-LAST:event_Urgent_inActionPerformed

    private void Hot_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hot_inActionPerformed
       hot_in = (Integer)Hot_in.getSelectedItem();
    }//GEN-LAST:event_Hot_inActionPerformed

    private void Num_failed_logins_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_failed_logins_inActionPerformed
       num_failed_logins_in = (Integer)Num_failed_logins_in.getSelectedItem();
    }//GEN-LAST:event_Num_failed_logins_inActionPerformed

    private void Logged_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logged_inActionPerformed
       logged_in = (Integer)Logged_in.getSelectedItem();
    }//GEN-LAST:event_Logged_inActionPerformed

    private void Num_compromised_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_compromised_inActionPerformed
       num_compromised_in = (Integer)Num_compromised_in.getSelectedItem();
    }//GEN-LAST:event_Num_compromised_inActionPerformed

    private void Root_shell_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Root_shell_inActionPerformed
        root_shell_in = (Integer)Root_shell_in.getSelectedItem();
    }//GEN-LAST:event_Root_shell_inActionPerformed

    private void Su_attempted_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Su_attempted_inActionPerformed
        su_attempted_in = (Integer)Su_attempted_in.getSelectedItem();
    }//GEN-LAST:event_Su_attempted_inActionPerformed

    private void Num_root_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_root_inActionPerformed
       num_root_in = (Integer)Num_root_in.getSelectedItem();
    }//GEN-LAST:event_Num_root_inActionPerformed

    private void Num_file_creations_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_file_creations_inActionPerformed
       num_file_creations_in = (Integer)Num_file_creations_in.getSelectedItem();
    }//GEN-LAST:event_Num_file_creations_inActionPerformed

    private void Num_shells_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_shells_inActionPerformed
       num_shells_in = (Integer)Num_shells_in.getSelectedItem();
    }//GEN-LAST:event_Num_shells_inActionPerformed

    private void Num_access_files_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_access_files_inActionPerformed
        num_access_files_in = (Integer)Num_access_files_in.getSelectedItem();
    }//GEN-LAST:event_Num_access_files_inActionPerformed

    private void Num_outbound_cmds_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_outbound_cmds_inActionPerformed
       num_outbound_cmds_in = (Integer)Num_outbound_cmds_in.getSelectedItem();
    }//GEN-LAST:event_Num_outbound_cmds_inActionPerformed

    private void Is_host_login_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Is_host_login_inActionPerformed
      is_host_login_in = (Integer)Is_host_login_in.getSelectedItem();
    }//GEN-LAST:event_Is_host_login_inActionPerformed

    private void Is_guest_login_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Is_guest_login_inActionPerformed
        is_guest_login_in = (Integer)Is_guest_login_in.getSelectedItem();
    }//GEN-LAST:event_Is_guest_login_inActionPerformed

    private void Count_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Count_inActionPerformed
      count_in = (Integer)Count_in.getSelectedItem();
    }//GEN-LAST:event_Count_inActionPerformed

    private void Srv_count_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Srv_count_inActionPerformed
        srv_count_in = (Integer)Srv_count_in.getSelectedItem();
    }//GEN-LAST:event_Srv_count_inActionPerformed

    private void Serror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Serror_rate_inActionPerformed
       serror_rate_in = (Float)Serror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Serror_rate_inActionPerformed

    private void Srv_serror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Srv_serror_rate_inActionPerformed
        srv_serror_rate_in = (Float)Srv_serror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Srv_serror_rate_inActionPerformed

    private void Rerror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rerror_rate_inActionPerformed
        rerror_rate_in = (Float)Rerror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Rerror_rate_inActionPerformed

    private void Srv_Rerror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Srv_Rerror_rate_inActionPerformed
        srv_rerror_rate_in = (Float)Srv_Rerror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Srv_Rerror_rate_inActionPerformed

    private void Same_srv_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Same_srv_rate_inActionPerformed
       same_srv_rate_in = (Float)Same_srv_rate_in.getSelectedItem();
    }//GEN-LAST:event_Same_srv_rate_inActionPerformed

    private void Diff_srv_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diff_srv_rate_inActionPerformed
       diff_srv_rate_in = (Float)Diff_srv_rate_in.getSelectedItem();
    }//GEN-LAST:event_Diff_srv_rate_inActionPerformed

    private void Srv_diff_host_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Srv_diff_host_rate_inActionPerformed
        srv_diff_host_rate_in = (Float)Srv_diff_host_rate_in.getSelectedItem();
    }//GEN-LAST:event_Srv_diff_host_rate_inActionPerformed

    private void Dst_host_count_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_count_inActionPerformed
        dst_host_count_in = (Integer)Dst_host_count_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_count_inActionPerformed

    private void Dst_host_srv_count_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_srv_count_inActionPerformed
       dst_host_srv_count_in = (Integer)Dst_host_srv_count_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_srv_count_inActionPerformed

    private void Dst_host_same_srv_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_same_srv_rate_inActionPerformed
        dst_host_same_srv_rate_in = (Float)Dst_host_same_srv_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_same_srv_rate_inActionPerformed

    private void Dst_host_diff_srv_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_diff_srv_rate_inActionPerformed
        dst_host_diff_srv_rate_in = (Float)Dst_host_diff_srv_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_diff_srv_rate_inActionPerformed

    private void Dst_host_same_src_port_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_same_src_port_rate_inActionPerformed
       dst_host_same_src_port_rate_in = (Float)Dst_host_same_src_port_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_same_src_port_rate_inActionPerformed

    private void Dst_host_srv_diff_host_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_srv_diff_host_rate_inActionPerformed
       dst_host_srv_diff_host_rate_in = (Float)Dst_host_srv_diff_host_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_srv_diff_host_rate_inActionPerformed

    private void Dst_host_serror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_serror_rate_inActionPerformed
        dst_host_serror_rate_in = (Float)Dst_host_serror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_serror_rate_inActionPerformed

    private void Dst_host_srv_serror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_srv_serror_rate_inActionPerformed
       dst_host_srv_serror_rate_in = (Float)Dst_host_srv_serror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_srv_serror_rate_inActionPerformed

    private void Dst_host_rerror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_rerror_rate_inActionPerformed
        dst_host_rerror_rate_in = (Float)Dst_host_rerror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_rerror_rate_inActionPerformed

    private void Dst_host_srv_rerror_rate_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dst_host_srv_rerror_rate_inActionPerformed
      dst_host_srv_rerror_rate_in = (Float)Dst_host_srv_rerror_rate_in.getSelectedItem();
    }//GEN-LAST:event_Dst_host_srv_rerror_rate_inActionPerformed

    private void SendPacketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPacketActionPerformed
        p1 = c2.createPacket(duration_in,protocol_type_in,service_in,flag_in,src_bytes_in,dst_bytes_in,land_in,wrong_fragment_in,urgent_in,
                hot_in,num_failed_logins_in,logged_in,num_compromised_in,root_shell_in,su_attempted_in,num_root_in,num_file_creations_in,
                num_shells_in,num_access_files_in,num_outbound_cmds_in,is_host_login_in,is_guest_login_in,count_in,srv_count_in,
                serror_rate_in,srv_serror_rate_in,rerror_rate_in,srv_rerror_rate_in,same_srv_rate_in,diff_srv_rate_in,srv_diff_host_rate_in,
                dst_host_count_in,dst_host_srv_count_in,dst_host_same_srv_rate_in,dst_host_diff_srv_rate_in,dst_host_same_src_port_rate_in,
                dst_host_srv_diff_host_rate_in,dst_host_serror_rate_in,dst_host_srv_serror_rate_in,dst_host_rerror_rate_in,dst_host_srv_rerror_rate_in);
        c2.sendPacket(p1);
    }//GEN-LAST:event_SendPacketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSendPacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSendPacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSendPacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSendPacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSendPacket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Count_in;
    private javax.swing.JComboBox Diff_srv_rate_in;
    private javax.swing.JComboBox Dst_bytes_in;
    private javax.swing.JComboBox Dst_host_count_in;
    private javax.swing.JComboBox Dst_host_diff_srv_rate_in;
    private javax.swing.JComboBox Dst_host_rerror_rate_in;
    private javax.swing.JComboBox Dst_host_same_src_port_rate_in;
    private javax.swing.JComboBox Dst_host_same_srv_rate_in;
    private javax.swing.JComboBox Dst_host_serror_rate_in;
    private javax.swing.JComboBox Dst_host_srv_count_in;
    private javax.swing.JComboBox Dst_host_srv_diff_host_rate_in;
    private javax.swing.JComboBox Dst_host_srv_rerror_rate_in;
    private javax.swing.JComboBox Dst_host_srv_serror_rate_in;
    private javax.swing.JComboBox Duration_in;
    private javax.swing.JComboBox Flag_in;
    private javax.swing.JComboBox Hot_in;
    private javax.swing.JComboBox Is_guest_login_in;
    private javax.swing.JComboBox Is_host_login_in;
    private javax.swing.JComboBox Land_in;
    private javax.swing.JComboBox Logged_in;
    private javax.swing.JComboBox Num_access_files_in;
    private javax.swing.JComboBox Num_compromised_in;
    private javax.swing.JComboBox Num_failed_logins_in;
    private javax.swing.JComboBox Num_file_creations_in;
    private javax.swing.JComboBox Num_outbound_cmds_in;
    private javax.swing.JComboBox Num_root_in;
    private javax.swing.JComboBox Num_shells_in;
    private javax.swing.JComboBox Protocol_type_in;
    private javax.swing.JComboBox Rerror_rate_in;
    private javax.swing.JComboBox Root_shell_in;
    private javax.swing.JComboBox Same_srv_rate_in;
    private javax.swing.JButton SendPacket;
    private javax.swing.JComboBox Serror_rate_in;
    private javax.swing.JComboBox Service_in;
    private javax.swing.JComboBox Src_bytes_in;
    private javax.swing.JComboBox Srv_Rerror_rate_in;
    private javax.swing.JComboBox Srv_count_in;
    private javax.swing.JComboBox Srv_diff_host_rate_in;
    private javax.swing.JComboBox Srv_serror_rate_in;
    private javax.swing.JComboBox Su_attempted_in;
    private javax.swing.JComboBox Urgent_in;
    private javax.swing.JComboBox Wrong_fragment_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
